services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DB=pet_commerce
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
    - ./mysql_data:/var/lib/mysql
  
  pet-commerce:
    image: pet-commerce:latest
    environment:
    - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - 8080:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:8080
